docs/merge-homebrew-core.md

merge-homebrew-core throws an uncommented list of conflicting files when final `git commit` is executed.

merge-homebrew-core: factual fixes

---

docs/merge-homebrew-core.md

In the original documentation I made a typo: `HOMEBREW_NO_AUTO_UPDATES` instead of `HOMEBREW_NO_AUTO_UPDATE`. :(

merge-homebrew-core: fix HOMEBREW_NO_AUTO_UPDATE

---

cmd/brew-build-bottle-pr.rb

Missing a comma.
```bash
% brew build-bottle-pr --dry-run ratfor
Error: /home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-developer/cmd/brew-build-bottle-pr.rb:101: syntax error, unexpected '\n', expecting &. or :: or '[' or '.'
/home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-developer/cmd/brew-build-bottle-pr.rb:133: syntax error, unexpected end-of-input, expecting keyword_end
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/linuxbrew/.linuxbrew/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.rb:24:in `require?'
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.rb:100:in `<main>'
```

build-bottle-pr: Fix syntax error

---

cmd/brew-build-bottle-pr.rb

When we submit PRs to build bottles, CI builds will fail when formula don't pass audit checks. We should run audit automatically before submitting a PR... hence, this PR :)

brew-build-bottle-pr: audit formulae before submitting PRs

---

docs/merge-homebrew-core.md

When merging Homebrew, conflicting files (formulas) are, in fact,
commented out. So, we correct this here.
Add paragraph on building bottles for conflicting formulas.

merge-homebrew-core.md: improvements and additions

---

docs/merge-homebrew-core.md

meld is no longer available because it was moved to a Cask upstream.

merge-homebrew-core: Update for removal of meld

---

cmd/brew-merge-homebrew.rb

The idea is that with this change we should be able to use the following syntax:
```
brew merge-homebrew --core sha1 sha2 sha3
```
and it should create the following merge commits:
`origin -> sha1`, `sha1 -> sha2`, `sha2 -> sha3`
Further improvements will be to automatically split homebrew commits into patches based on which formulas are updated

brew-merge-homebrew: specify several merges in one command

---

cmd/brew-pull-circle.rb

Fix punctuation, specifically + and @, in bottle filenames.
Replace %2B with + and %40 with @.

pull-circle: Fix punctuation in bottle filenames

---

cmd/brew-pull-circle.rb

pull-circle: add --overwrite option to overwrite artifacts on Bintray
merge-homebrew: signature of `git_merge` function contained the default
value of `fast_forward` as `fast_forward: value`. This PR changes this
behavior to `fast_forward = value`.

pull-circle: add --overwrite option to overwrite published bottles on Bintray

---

cmd/brew-merge-homebrew.rb

Since all of dupes is not part of core, this is now unnecessary.

merge-homebrew: Remove option to merge dupes

---

.travis.yml

Clone Linuxbrew rather than Homebrew, since otherwise there's a
lot of spurious errors from core.
Also drop osx_image from matrix, because Travis doesn't recognize
it.

.travis.yml: Fix Linux runs

---

README.md

We say it's a "Linuxbrew" document but were pointing to Homebrew.

README.md: use Linuxbrew docs for external commands

---

README.md
cmd/brew-travis-debug.rb

This imports rwhogg/travis-debug into Linuxbrew.
I've rewritten it in Ruby rather than the original, which was in idiosyncratic Python. <strike>Also, it inlines the Dockerfile to avoid polluting the repo.</strike>
EDIT: It now uses https://github.com/Linuxbrew/docker/blob/master/travis/Dockerfile for its Dockerfile

Add travis-debug command

---

cmd/brew-merge-homebrew.rb

Add help saying that you can specify an upstream sha1 commit id to merge only up to that id.

merge-homebrew: update command line help

---

cmd/brew-build-bottle-pr.rb

<strike>
A lot of formulae are missing tests upstream, causing
audit failures. This provides a way for maintainers to
ignore them when submitting bottling PR's while
upstream finishes working on
https://github.com/Homebrew/homebrew-core/issues/11898
</strike>
This PR is now about `brew build-bottle-pr` doing an online audit rather than a strict audit so missing tests (of which there are a lot) don't prevent making the PR.

build-bottle-pr: Do online rather than strict audit

---

cmd/brew-test-bot-docker.rb

Prevent `docker cp` from copying the entire Linuxbrew installation
from the Docker container to the local machine.

test-bot-docker: Store bottles in a subdirectory

---

cmd/brew-travis-debug.rb

Avoid deprecation warning.
Fix error:
```
Error: Calling Homebrew#travis_debug is deprecated!
Use 'module_function' or 'def self.travis_debug' to convert it to a class method instead.
/home/linuxbrew/.linuxbrew/Library/Taps/linuxbrew/homebrew-developer/cmd/brew-travis-debug.rb:14:in `<top (required)>'
Please report this to the linuxbrew/developer tap!
```

travis-debug: Use module_function

---

cmd/brew-build-bottle-pr.rb

However, allow formulae that depend on specific versions
of macOS.
Test cases: `terminal-notifier` (should block), `gnu-apl` (should allow).

build-bottle-pr: Skip formulae that depend on macOS

---

cmd/brew-build-bottle-pr.rb

build-bottle-pr: Rescue NameError when MacOSRequirement is not defined

---

cmd/brew-test-bot-docker.rb

This is needed to build bottles that need formulae
from homebrew-xorg (for example vtk).

brew-test-bot-docker: tap linuxbrew/homebrew-xorg

---

cmd/brew-pull-linux.rb

Fixes the following error caused by not following redirects while fetching the patch:
```
/usr/local/bin/brew pull-linux --bottle -vd https://github.com/Homebrew/homebrew-science/pull/6194
==> Fetching patch 
Patch: https://github.com/Homebrew/homebrew-science/pull/6194.patch
/usr/bin/curl --show-error --user-agent Homebrew/1.3.1-97-g6d393de (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail https://github.com/Homebrew/homebrew-science/pull/6194.patch -s -o /Users/jonchang/Library/Caches/Homebrew/6194.patch
==> Applying patch
git am --whitespace=fix -3 /Users/jonchang/Library/Caches/Homebrew/6194.patch
Patch format detection failed.
fatal: Resolve operation not in progress, we are not resuming.
Error: Patch failed to apply: aborted.
Error: Kernel.exit
```

pull-linux: temp fix for patch redirects

---

cmd/brew-merge-homebrew.rb

Use "git mergetool" if HOMEBREW_MERGETOOL is set.
I'm not a fan of resolving conflicts with a normal
editor.
Closes #43

merge-homebrew: Allow using git mergetool

---

cmd/brew-pull-circle.rb

Better would be to continue the existing download, but CircleCI oddly
doesn't seem to support resuming.
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

pull-circle: Skip existing files

---

cmd/brew-build-bottle-pr.rb

This allows to speed up the command a lot (no url checks anymore, which are really slow when a formula has a lot of resources).
Audit failures are quite rare, and the audit is run on the CI anyway.

brew-build-bottle-pr: remove online audit step

---

cmd/brew-build-bottle-pr.rb

When building a bottle PR, we should be ignoring cases like:
depends_on :macos => :lion
One solution would be to safeguard all these lines with an "OS.mac?"
check, but as I am running this on my mac, it does not make sense.

brew-build-bottle-pr: ignore minimum mac os requirements

---

cmd/brew-build-bottle-pr.rb

This was failing with:
Error: undefined method `dry_run?' for ["boost-python3"]:Array
linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-developer/cmd/brew-build-bottle-pr.rb:153:in `block (2 levels) in build_bottle'
linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-developer/cmd/brew-build-bottle-pr.rb:150:in `open'

brew-build-bottle-pr: Fix command

---

cmd/brew-build-bottle-pr.rb

- We only need the description in the PR to appease the bot that tells
us to be more verbose in PR/issue commentary.
- Having it in the commit message caused us to have to strip it out when
using `brew squash-bottle-pr`, which was a pain. This change was
suggested in a review by @sjackman on #100.
Co-authored-by: Shaun Jackman <sjackman@gmail.com>

build-bottle-pr: We don't need the description in the commit message

---

azure-pipelines.yml

- There have been lots of changes that `Homebrew/linuxbrew-core` have in
formulae that aren't in the archived `Linuxbrew/brew` repo, for
example:
```
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/reminiscence.rb
reminiscence: undefined method `uses_from_macos' for #<Class:0x00000000041f3638>
```
- :crossed_fingers: :pray:

azure-pipelines: `git clone Homebrew/brew` not `Linuxbrew/brew`

---

cmd/brew-merge-homebrew.rb

- At the moment, on the rare occasions when the formulae we merge don't
have conflicts, the PR description is empty which makes request-info-bot
in linuxbrew-core complain.

merge-homebrew: Make the merge PR description better

---

cmd/brew-squash-bottle-pr.rb

- The setting for the commit to take the author from was `HEAD~1`, which
is the "# Build a bottle for Linuxbrew" commit in most cases. These
commits are authored by maintainers, so then the bottle commits show
up to be from the previous author, too.
- This accident lead to us artificially inflating the number of
_authorship_ commits a maintainer has. :-( For an example, see:
https://github.com/Homebrew/linuxbrew-core/commits/2e7e3d3d46ef09bc308f39b095f54ac2e54ded8f
- they all show up as from me.
- Instead, the script now determines the author from `HEAD`, which is
the _current_ bottle SHA commit, which is, at the start, before the
squash, authored by `LinuxbrewTestBot`.

squash-bottle-pr: Fix bug with determining the author of a bottle commit

---

cmd/brew-find-formulae-to-bottle.rb

- For every merge between Homebrew/homebrew-core and Homebrew/linuxbrew-core we do, there are conflicting formulae, mostly in the `bottle do` blocks. For every one of those conflicitng formulae, we have to do `brew build-bottle-pr`. To do this, we have to copy/paste every conflicting formula line from the commit message/PR description as an argument to `brew build-bottle-pr`, which gets tedious.
- For every merge commit (nothing sophisticated, just "does it start with 'Merge branch homebrew/master into linuxbrew/master'?"), this script will trim the Conflict lines if there are any and output a list of formulae to stdout.
- For building bottle PRs from that list, you can then use a bash for loop, like:
`for i in $(brew find-formulae-to-bottle); do brew build-bottle-pr $i; done`. …

Extract a list of conflicting formulae from the latest merge commit

---

cmd/brew-find-formulae-to-bottle.rb

- Addresses [a comment from review of #108](https://github.com/Linuxbrew/homebrew-developer/pull/108#pullrequestreview-272105278).

find-formulae-to-bottle: Skip commit message lines that aren't "Formula/thing.rb"

---

cmd/brew-squash-bottle-pr.rb

- We programatically determined this in
https://github.com/Linuxbrew/homebrew-developer/pull/100 because
bottle commits appeared to be authored by whichever maintainer was
pulling the bottle.
- That didn't work 100% accurately, so we tried to fix it to pull from
the _bottle commit itself_ before the squash - ie always authored by
LinuxbrewTestBot. That happened in
https://github.com/Linuxbrew/homebrew-developer/pull/107, and also
didn't work 100% reliably.
- Let's cut our losses and stop the mis-authoring of bottle commits
by hardcoding `LinuxbrewTestBot` as the author. Given that this script
is used when maintainers pull bottle commits AND the PR that made the
bottle commit happen was a simple `# Build a bottle for Linuxbrew`
commit which gets rebased away, we will never be in a …

squash-bottle-pr: Hardcode the commit author as LinuxbrewTestBot

---

cmd/brew-build-bottle-pr.rb

- Remove CircleCI `--keep-old` test-bot config as we're on Azure mostly
now.
- Don't tell users they should `brew upgrade --devel hub` as options are
deprecated.

build-bottle-pr: no more formula options, and we don't use Circle anymore

---

cmd/brew-build-bottle-pr.rb
cmd/brew-find-formulae-to-bottle.rb

- In doing https://github.com/Homebrew/linuxbrew-core/pull/14838 (a GitHub Action for `brew
build-bottle-pr`), concerns were raised about a bot with access to our
repos being able to rewrite formulae and bottle PRs.
- In this refactor, all of the `brew` "check these things about these
formulae to see if they're OK to bottle" is done in the
`find-formulae-to-bottle` step, rather than the `brew
build-bottle-pr`, so the script that writes commits and raises pull
requests doesn't have to run any `brew` commands itself, so the
formulae are never loaded.
- I think I've taken everything necessary out - things seem to work. I
also reject formulae that can't be bottled, which removes them from the
final list of formulae that are shown for `brew build-bottle-pr`.

Refactor bits of build-bottle-pr into find-formulae-to-bottle

---

cmd/brew-build-bottle-pr.rb

- After the recent large refactor (b9cf70c), this script only accepts
one formula specified at a time. Therefore, it doesn't need `--limit`
or any of the counting logic to work out if we're over GitHub's limits.

build-bottle-pr: Remove unnecessary `--limit` argument

---

README.md

- The documentation has been moved to Homebrew/brew in the [Homebrew/linuxbrew-core Maintainer Guide](https://docs.brew.sh/Homebrew-linuxbrew-core-Maintainer-Guide).

Remove "Documentation" section from the README

---

cmd/brew-build-bottle-pr.rb

- This will no longer default to `origin`. I preferred it when it did,
but this is based on feedback in
https://github.com/Homebrew/brew/pull/6448#discussion_r324248081.
- Now, the GitHub Action can employ the same syntax as local maintainer
usage:
- `brew build-bottle-pr --remote=origin formula`
- `brew build-bottle-pr --remote=$HOMEBREW_GITHUB_USER formula`

build-bottle-pr: Make the `--remote` argument mandatory

---

README.md

Change Linuxbrew/developer to Homebrew/linux-dev where appropriate
Because this repo is now under Homebrew, change the link pointing to Linuxbrew documentation.

README.md: account for the new repo name (homebrew/linux-dev)

---

cmd/brew-test-bot-docker.rb

- The `linuxbrew/brew` one will soon be deprecated.

Use the homebrew/brew Docker image in `brew test-bot-docker`

---

README.md
cmd/brew-announce.rb
cmd/brew-build-bottle-pr.rb
cmd/brew-squash-bottle-pr.rb

- We're moving away from the Linuxbrew name to Homebrew on Linux. Most
of our docs say Homebrew on Linux. Linuxbrew _feels weird_ especially
in bottle PRs.

build-bottle-pr: Use "Linux" instead of "Linuxbrew"

---

cmd/brew-find-formulae-to-bottle.rb

For example `go` formula has a line `depends_on :macos => :el_capitan`
even though it does not depend on macos and builds just fine on linux.
Also, if a formula is truly macOS only, then I guess we wouldn't get
any conflicts regarding these formulae, because we simply do not touch
them.

find-formulae-to-bottle: do not check if depends on macos

---

cmd/brew-build-bottle-pr.rb
cmd/brew-find-formulae-to-bottle.rb

I think it could be a nice failsafe, to first check if a PR is already opened with given title.
Also the `--force` option would need to be redefined as: 'when passed, do not check for opened PRs' and the branch deletion would become the default then.

build-bottle-pr: check for open PRs

---

cmd/brew-check-for-deleted-upstream-core-formulae.rb

- Homebrew/linuxbrew-core's merge process doesn't account for upstream formulae deletions very well - most often presenting them as conflicts - and we have to go back later with shell commands to find them and raise PRs to delete them.
- Here's a quick script to find the upstream deleted formulae. It doesn't auto-delete them (stretch goal?), but it's a consistent start for all Linux maintainers to be able to find them.
- Obviously, it excludes Linux-only formulae present in Homebrew/linuxbrew-core.

Find formulae that have been deleted in Homebrew/homebrew-core

---

cmd/brew-check-for-deleted-upstream-core-formulae.rb

With this change, it is possible to make use of `homebrew/master` branch (which we already have set up for merges).
If no parameters are passed to the script, it checks out `homebrew/master` branch to get the list of available formulae in `homebrew-core`, then switches to `master` to get the list of formulae from `linuxbrew-core` while excluding those linux specific ones.
I tried not to break the existing functionality and it seems to be kept.

brew-check-for-deleted: support one repo workflow

---

cmd/brew-find-not-bottled.rb

With this script, one can easily find a list of formulae that do not have a linux bottle. It will filter out those formulae that are marked as `bottle :unneeded`. Also as an option, one can pass an additional regexp that must be found in a formula or not.
I know this could be done with just plain grep, but I think it is nice to have it here already in place ready to use.

Add brew-find-not-bottled command

---

cmd/brew-build-bottle-pr.rb

cmd/brew-build-bottle-pr.rb: cleanup after 3894315

---

.github/workflows/check_style.yml

Should fix the situation, where workflow job would fail, when run in a
repo fork, because of non-existent directory.

workflow: mkdir directory before copying to it

---

cmd/brew-build-bottle-pr.rb

The description says that `remote` defaults to `origin` but the code says otherwise. Here, I'm syncing code with description since it makes sense for `remote` to default to `origin`.

cmd/brew-build-bottle-pr.rb: sync with description

---

cmd/brew-announce.rb
cmd/brew-build-bottle-pr.rb
cmd/brew-check-for-deleted-upstream-core-formulae.rb
cmd/brew-find-formulae-to-bottle.rb
cmd/brew-find-not-bottled.rb
cmd/brew-merge-homebrew.rb
cmd/brew-migrate-formula.rb
cmd/brew-squash-bottle-pr.rb
cmd/brew-test-bot-docker.rb

Reverts Homebrew/homebrew-linux-dev#137
The fix for the `--help` text was reverted in https://github.com/Homebrew/brew/pull/6988  and I don't know how much time fixing the broken thing mentioned there will take.

Revert "Switch from using ARGV to Homebrew.args"

---

cmd/request-bottle.rb

Includes the user and email of the person requesting the bottle, for use in the commit workflow on Homebrew/linuxbrew-core.

request-bottle: include user and email in payload

---

cmd/request-bottle.rb

Should prevent situations like this: https://github.com/Homebrew/linuxbrew-core/commit/4840e6102cf2e378471394d4b206134e5f5bbf45

request-bottle: die if user or email is empty

---

cmd/request-bottle.rb

- For auto-builds on GitHub Actions from merge commits, this used to set
the co-authored-by line to the (Linux)BrewTestBot user.
- We do however want _some_ maintainer accountability for the actions of
our bots, so set this to the author of the previous merge commit so
there's a visible human involved.

request-bottle: On CI, use merge commit author for co-author

---

cmd/merge-homebrew.rb

I think it might be useful to have this information printed.
Can have a quick glance at the merge, without analyzing the log.

merge-homebrew: print added and deleted formulae

---

cmd/find-not-bottled.rb

- We can't build them on Linux.
- Not using `depends_on :macos` because there are some that _do_ work.

find-not-bottled: Exclude formulae that depend on XCode

---

cmd/check-for-deleted-upstream-core-formulae.rb

- Since https://github.com/Homebrew/linuxbrew-core/commit/6578a4aa86b80816cf0553f1d45828c0072197a4, we're using the proper `depends_on` DSL to specify Linux-only formulae.

check-deleted-upstream-formulae: Fix Linux-only formula detection

---

cmd/find-not-bottled.rb

This will help using `find-not-bottled` on macOS machines.

find-not-bottled: optionally specify a tap

---

cmd/pull-macos.rb

Tried to apply this upstream: https://github.com/Homebrew/brew/pull/7070
But it got reverted, because of some issues with Jenkins: https://github.com/Homebrew/brew/pull/7077
- `merge_commit?` function needed to be overridden with one small change: `origin` -> `homebrew`.
- `HOMEBREW_BOTTLE_DOMAIN` needs to be set again here, because it's only set in `brew.sh` earlier
I'm using this script right now, to pull some bottles and it works fine.
`brew pull-macos PR_NUMBER`

add pull-macos script

---

cmd/request-bottle.rb

This PR simply modifies the script to allow passing of multiple formulae.
It means we can use `xargs` instead of `xargs -n1` in CI for example.

request-bottle: allow multiple formulae

---

cmd/merge-homebrew.rb

- In all my time working on Homebrew, I've never *not* appended `--skip-style` to my `brew merge-homebrew --core` commands.
- Therefore, this makes *not* running `brew style` be the default as it feels weird to *always* specify skipping something.

merge-homebrew: Make skipping `brew style` the default

---

cmd/request-bottle.rb

This will permit the dispatch-build-bottle job to post to issues when the job fails. See these commits:
https://github.com/Homebrew/linuxbrew-core/commit/5c467257f826b730ab66901afff1d32ff6f1913d
https://github.com/Homebrew/linuxbrew-core/commit/06c199d8af10533da011e2901751c2bdcace7a14
And this pull request as an example of what it would look like:
https://github.com/Homebrew/linuxbrew-core/pull/19873

request-bottle: add issue number option to payload

---

cmd/request-bottle.rb

This shows up in the Actions tab, so it should be easier to scan for what you're looking for in the case where you're looking for a build that test bot didn't ping you for.

request-bottle: use better event names

---

cmd/fetch-failed-logs.rb

This script fetches latest build failures logs from GitHub Actions API for given formula.
Supports `repository_dispatch` (`--dispatched` option) and `pull_request` events.
Example:
```
➜  ~  brew fetch-failed-logs imapsync --dispatched
==> Workflow run id: 67726873
==> brew test imapsync --verbose
Testing imapsync
==> /home/linuxbrew/.linuxbrew/Cellar/imapsync/1.977/bin/imapsync --dry
Can't locate Socket6.pm in @INC (you may need to install the Socket6 module) (@INC contains: /home/linuxbrew/.linuxbrew/Cellar/imapsync/1.977/libexec/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl …
```

add fetch-failed-logs script

---

cmd/fetch-failed-logs.rb

I believe it should be `Homebrew.args` instead of plain `args` ... no?

fetch-failed-logs.rb: `args` -> `Homebrew.args`

---

README.md

- Begin descriptions with a verb in Infinitive form (without "to").
- add `linuxbrew-core` link
- add description for `fetch-failed-logs` (CC @dawidd6)

README.md: standardize + add fetch_failed_logs

---

cmd/fetch-failed-logs.rb

I've broken this up into several commits, but these were originally written all at once so the individual commits might not be testable on their own.
The main new features are:
* permit keeping log files around with `--keep-tmp`
* fetch multiple failures per log file
* strip out ANSI control codes if stdout isn't a terminal (also respecting `HOMEBREW_COLOR` and `HOMEBREW_NO_COLOR`)
* optional markdown output (which also strips ansi control codes) so you can `brew fetch-failed-logs <formula> | pbcopy` then paste it into a github issue.... or for actions to do something similar ;)

fetch-failed-logs: multiple improvements

---

cmd/merge-homebrew.rb

Currently core merges are only possible on Linux. This pull request permits `brew merge-homebrew --core` to work on macOS as well.
When running on macOS, `brew merge-homebrew --core` will search the installed taps for a Homebrew/linuxbrew-core remote, and uses that as the core tap when merging. On Linux, the behavior is unchanged.
(I have linuxbrew/core tapped on my macOS machine with `brew tap homebrew/linux https://github.com/Homebrew/linuxbrew-core`)

merge-homebrew: permit core merges on macOS

---

cmd/merge-homebrew.rb

When merge conflicts are detected within `bottle do` blocks, this pull request will automatically pick the upstream side of the merge conflict. It leaves merge conflicts found elsewhere in the file to the maintainer. Because the file is marked as a merge conflict, it should still show the file to the maintainer, so it's not completely automatic and there's another human check to make sure that nothing evil has happened.
Note that this uses the Ruby flip-flop operator. Even though RuboCop would prefer that we avoid this operator, there's no cleaner way to operate over a range of lines without building some ugly state machine, especially given that we have nested flip-flops. Those RuboCop warnings are also silenced here.

merge-homebrew: autofix conflicts in bottle blocks

---

Dockerfile

See https://github.com/Homebrew/homebrew-linux-dev/pull/177#issuecomment-670225424

Dockerfile: Bump Git from version 2.18.0 to 2.28.0

---

cmd/announce.rb

Fix `Error: Calling args.resolved_formulae is deprecated! Use args.named.to_resolved_formulae instead.`

Fix announce: args.resolved_formulae is deprecated

---

cmd/merge-homebrew.rb

Fixes:
Error: Calling `max_named` is deprecated! Use `named_args max:` instead.
Please report this issue to the homebrew/linux-dev tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/merge-homebrew.rb:26

merge-homebrew: use named_args max

---

cmd/fetch-failed-logs.rb

Fixes:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/fetch-failed-logs.rb:57:7: C: [Correctable] Argument " " is redundant because it is implied by default.
line.split(" ")[1..]&.join(" ")

fetch-failed-logs: fix style

---

cmd/request-bottle.rb

Fixes:
Error: Calling GitHub.open_api is deprecated! Use GitHub::API.open_rest instead.

request-bottle: fix deprecation

---

cmd/not-migrated.rb

This command can *in theory* help us with all those migration stuff to homebrew-core of linux-specific changes.
It prints `git diff`s between homebrew-core/master and linuxbrew-core/master refs. I recommend using `--limit` flag to (well) limit the number of non-empty diffs displayed. Because without named arg (formula) the command will print all the diffs.
I recommend piping the output to `bat` or something like that, because the output is plain, no colorization.

cmd: add not-migrated command

---

cmd/check-for-deleted-upstream-core-formulae.rb
cmd/find-formulae-to-bottle.rb
cmd/find-not-bottled.rb

Fixes:
Calling `max_named` is disabled! Use `named_args max:` instead.

cmds: use max_named

---

cmd/merge-homebrew.rb

Right now I am adding a comment after each linuxbrew-core bottle with:
`ls | xargs grep -L "# linuxbrew-core" | xargs sed -i '' 's/.*x86_64_linux.*/& # linuxbrew-core/g' ; git add . ; git commit -m "formulae: add comment to bottle line to generate conflicts on next merge"`
after each merge. This allows to get rid of homebrew-core linux formulae when merging.

merge-homebrew: delete homebrew-core bottles on merge

---

Dockerfile

This was needed for https://github.com/Homebrew/homebrew-portable-ruby/pull/127 so I thought it might be useful here too.

Dockerfile: add bzip2.

---

Dockerfile

Brew doctor complains (and fails in homebrew-core) because of unbrewed stuff installed to /usr/local
Also, don't symlink curl: we should be able for force brew to use the /opt one with an ENV variable

wheezy: install curl to /opt

---

Dockerfile

The issue with curl and certificated is probably somewhere else.
See https://github.com/Homebrew/homebrew-test-bot/pull/786

wheezy: no need for newest curl
