Homebrew/homebrew-linux-dev

cmd/brew-build-bottle-pr.rb
Redo of #2 after history got rewritten
=> build-bottle-pr: Add help text

LICENSE
Redo of #3 after history got rewritten
=> LICENSE: update the copyright year

cmd/brew-pull-bottle.rb
Merge a pull request and update both the Mac and Linux bottles.
=> Add brew-pull-bottle.rb

README.md
#9 added the pull-bottle command; this lists it in the README.
=> README.md: document the pull-bottle command

README.md, docs/merge-homebrew-core.md
First draft of a document on how to merge Homebrew/homebrew-core to Linuxbrew/homebrew-core.
=> docs/merge-homebrew-core: first draft

cmd/brew-build-bottle-pr.rb
=> brew-build-bottle-pr: fix warning message

cmd/brew-build-bottle-pr.rb
* Delete local `bottle-<formula>` branch if it exists
This branch might exist  due to a failed attempt to build a
bottle in the past.
* Delete remote `your-fork/bottle-<formula>` branch it it exists
This branch might exist if a PR has not been submitted.
* Reorganize the code to make changes *after* we switch to a new branch
so that we don't leave uncommitted changes if something fails
=> brew-build-bottle-pr: improvements

cmd/brew-build-bottle-pr.rb
=> build-bottle-pr: Remove trailing whitespace

cmd/brew-build-bottle-pr.rb
This feature requires hub ≥ 2.3.0.
=> build-bottle-pr: Add assignee and label

cmd/brew-build-bottle-pr.rb
formula was an undefined variable. Pass it
as an argument.
=> build-bottle-pr: Fix running in verbose mode

cmd/brew-build-bottle-pr.rb
=> build-bottle-pr: Fix style

cmd/brew-test-bot-docker.rb
When used with a pull request URL, fix the error:
Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
=> test-bot-docker: git config user.name and user.email

cmd/brew-pull-linux.rb
Rename BINTRAY_KEY to HOMEBREW_BINTRAY_KEY.
=> pull-linux: Rename BINTRAY_USER to HOMEBREW_BINTRAY_USER

cmd/brew-migrate-formula.rb
Migrate formulae to a new tap.
=> migrate-formula: New command

cmd/brew-migrate-formula.rb
Don't create the add PR. Do create the remove PR.
=> migrate-formula: Migrate a formula that exists

cmd/brew-build-bottle-pr.rb
as only this part is needed (and commented out)
=> brew-build-bottle-pr: write only the title to the file

docs/merge-homebrew-core.md
- We usually don't bother about `brew style` (someone can do that separately if they want to).
- There's now `brew find-formulae-to-bottle` to extract a list of conflicting formulae from merge commits.
- The `merge-homebrew` command opens the PR for us automatically.
=> Docs: Update merge-homebrew docs to reflect the current merge practices

cmd/brew-build-bottle-pr.rb
Merge with https://github.com/Homebrew/brew/pull/6366.
=> Rename `minimum_version_specified` to `version_specified`.

azure-pipelines.yml, cmd/brew-find-formulae-to-bottle.rb, cmd/brew-merge-homebrew.rb, cmd/brew-pull-circle.rb, cmd/brew-test-bot-docker.rb
=> azure-pipelines.yml: Run brew style

cmd/brew-squash-bottle-pr.rb
This PR should fix situations like these:
https://github.com/Homebrew/linuxbrew-core/commit/17512fa3b3a84ed03272d5d1267fdb4ab5b6ac8d
https://github.com/Homebrew/linuxbrew-core/commit/f14d6ab4d21e251938dd0f498042bcb1ab6f1f6b
=> squash-bottle-pr: fix marker

.github/workflows/check_style.yml
I tried to delete `azure-pipelines.yml` but then the check was freezing, so I guess it would be better to do that directly on `master` after merging this PR.
=> Switch from Azure to Github Actions

cmd/brew-build-bottle-pr.rb
https://github.com/Homebrew/brew/pull/6939
=> build-bottle-pr: fix --force option detection

.github/workflows/check_style.yml
=> GitHub Actions: don't run in forks

cmd/brew-announce.rb, cmd/brew-build-bottle-pr.rb, cmd/brew-check-for-deleted-upstream-core-formulae.rb, cmd/brew-find-formulae-to-bottle.rb, cmd/brew-find-not-bottled.rb, cmd/brew-merge-homebrew.rb, cmd/brew-migrate-formula.rb, cmd/brew-squash-bottle-pr.rb, cmd/brew-test-bot-docker.rb
- Homebrew is gradually switching to its own argument parser rather than using ARGV: https://github.com/Homebrew/brew/issues/5730
- This is still a work in progress as there are a lot of scripts here!
=> Switch from using ARGV to Homebrew.args

cmd/brew-build-bottle-pr.rb
See
https://github.com/Homebrew/linuxbrew-core/pull/19427
=> brew-build-bottle-pr: open pull requests against develop

cmd/announce.rb, cmd/check-for-deleted-upstream-core-formulae.rb, cmd/find-formulae-to-bottle.rb, cmd/find-not-bottled.rb, cmd/merge-homebrew.rb, cmd/migrate-formula.rb, cmd/request-bottle.rb, cmd/test-bot-docker.rb
Tightening up the option parsing to catch potential invalid usage, plus some style and grammar fixes.
=> commands: fix up option parsing

cmd/request-bottle.rb
See https://github.com/Homebrew/linuxbrew-core/runs/426925955?check_suite_focus=true for an example of it in action.
=> request-bottles: add --ignore-errors option

cmd/find-formulae-to-bottle.rb, cmd/merge-homebrew.rb, cmd/migrate-formula.rb, cmd/request-bottle.rb
- [`Layout/LineLength`](https://github.com/Homebrew/brew/commit/cd3ced48e97f8fdab67b0737ba5441d4057457e9) was reduced and [`Lint/AmbiguousOperator`](https://github.com/Homebrew/brew/commit/4498303f9a347184d9fc0bb6e93351bbfc4d1091) was enabled this weekend.
=> Fix new RuboCop style offenses

cmd/merge-homebrew.rb
This should spare us some headaches.
=> merge-homebrew: fix style by default

cmd/merge-homebrew.rb
This reverts commit d1bb55d98f09288de74ee464bb3d4a7d5b450b6e.
=> Revert "merge-homebrew: autofix conflicts in bottle blocks (#173)"

cmd/fetch-failed-logs.rb, cmd/find-formulae-to-bottle.rb
Remove special handling for global options.
=> Remove global options from parser.

cmd/request-bottle.rb
https://github.com/Homebrew/brew/pull/8456
cc @reitermarkus
=> request-bottle: handle latest breakage

cmd/request-bottle.rb
This should let us build bottles for e.g. xorg formulae.
See https://github.com/Linuxbrew/homebrew-xorg/pull/687
=> request-bottle: permit dispatching against taps

Dockerfile
=> Dockerfile: add gawk

Dockerfile
This reverts commit 62ad6b24ee9236c450a816734d47c17cd4a4b33f.
I actually need to add gawk to https://github.com/Homebrew/brew
=> Revert "Dockerfile: add gawk (#196)"

Dockerfile
https://github.com/Homebrew/homebrew-core/pull/79936
=> Dockerfile: setup Homebrew just like in the main image

Dockerfile
This is needed for `brew bottle`.
=> Dockerfile: compile newer tar from source

cmd/merge-homebrew.rb
While merging to linuxbrew-core, delete :all bottle blocks.
This allows to rebuild these linux bottles in a second pass
and to upload these github bottles to the right org
=> merge: remove :all bottle blocks

Dockerfile
Needed for https://github.com/Homebrew/homebrew-core/pull/94795
=> wheezy: install newest curl

README.md
Update readme with deprecation text as we will archive this repository
=> homebrew-linux-dev: deprecate
